stock_dashboard_api/views/mail_view.py
import json

from flask import render_template, redirect, url_for, request, Blueprint

from stock_dashboard_api.forms import EmailForm
from stock_dashboard_api.utils.send_email_queue import publish_email

mod = Blueprint('mail', __name__, url_prefix='/mail')


@mod.route('/')
@mod.route('/home')
def home():
    """
    Temporary main page.
    """
    return render_template('home.html')


@mod.route('/send_email', methods=['GET', 'POST'])
def send_email():
    """
    Handles a form that is used to send an email.
    """
    form = EmailForm()

    if form.validate_on_submit():
        sender = form.sender.data
        recipient = form.recipient.data
        path = request.endpoint

        body = json.dumps({"sender": sender,
                           "recipient": recipient,
                           "path": path,
                           "template_name": "dashboard_invite_email"})
        publish_email(body)

        return redirect(url_for('mail.home'))
    return render_template('send_email.html', form=form)

stock_dashboard_api/templates/email.html
<html>
<head>
    <style>
        * {
            text-align: center;
        }

        .head, .footer {
            background-color: lightblue;
            color: white;
        }

        .link {
            text-decoration: none;
            color: #2C66E1;
            padding: 5px;
            border: 3px solid lightblue;
            width: fit-content;
        }

        a {
            text-decoration: none;
            color: #2C66E1;
        }
    </style>
</head>
<body>
    <div class="head">
        <h1>Hello {{ recipient }}!</h1>
    </div>
    <br>
    <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
            <td align="center">
                <h2>You've been invited to view a Stock Dashboard at the following link:</h2>
            </td>
            <td align="center">
                <a href="{{ link }}" class="link">{{ link }}</a>
            </td>
        </tr>
    </table>
    <div class="footer">
        <h3>Visit our Stonks Dashboard at 127.0.0.1 port 5000.</h3>
    </div>
</body>
</html>

stock_dashboard_api/templates/home.html
<h1>This is the home page.</h1>
<a href="{{ url_for('mail.send_email') }}">Send an email.</a>

stock_dashboard_api/templates/send_email.html
<h1>This is the dashboard page.</h1>
<form action="" method="post" novalidate>
    {{ form.hidden_tag() }}
    <p>
        {{ form.sender.label }}<br>
        {{ form.sender(size=32) }}
    </p>
    <p>
        {{ form.recipient.label }}
        {{ form.recipient(size=64) }}
    </p>
    <p>
        {{ form.submit() }}
    </p>
    {% if form.errors %}
        {{ form.errors }}
    {% endif %}
</form>